services:
  mysql:
    image: mysql:8.0
    container_name: recruitment-mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: recruitment_db
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - recruitment-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  maildev:
    image: maildev/maildev
    container_name: recruitment-maildev
    ports:
      - "1080:1080"
      - "1025:1025"
    networks:
      - recruitment-network

  backend:
    build: ./backend
    container_name: recruitment-backend
    ports:
      - "8080:8080"
    depends_on:
      mysql:
        condition: service_healthy
      maildev:
        condition: service_started
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    volumes:
      - uploads:/app/uploads
    networks:
      - recruitment-network
    restart: unless-stopped

  frontend:
    build: ./frontend
    container_name: recruitment-frontend
    ports:
      - "4200:4200"
    depends_on:
      - backend
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
    networks:
      - recruitment-network
    restart: unless-stopped
    stdin_open: true
    tty: true

volumes:
  mysql_data:
  uploads:

networks:
  recruitment-network:
    driver: bridge